### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by JiweiTian** [JiaweiLian/CBA#1]
你好，
拜读了文章，对抗攻击的设计非常巧妙！
请问代码何时公布呀？多谢

**Comment by JiaweiLian** [comment]
感谢您的兴趣，我这两天抽空整理一下



---Original---
From: ***@***.***&gt;
Sent at: 2023年2月28日(Tue) Evening10:23
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JiaweiLian/CBA] 你好 (Issue #1)




 
你好，
 拜读了文章，对抗攻击的设计非常巧妙！
 请问代码何时公布呀？多谢

**Comment by JiaweiLian** [comment]
您好，代码已公布

**Comment by JiweiTian** [comment]
多谢博士，我也在西安的高校工作，做AI安全方面的研究，方便的话我们可以加个微信啥的不？

**Comment by JiaweiLian** [comment]
可以的，您稍等，我发您邮箱
